modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mgtlogin"
version="1.0.0-SNAPSHOT"
displayName="MGT-Login"
authors="GnomoMuitoLoco"
description='''Esse é um mod de login personalizado, oferecendo funcionalidades adicionais de segurança e autenticação.'''

[[dependencies.mgtlogin]]
modId="neoforge"
type="required"
versionRange="[21.1.211,)"
ordering="NONE"
side="BOTH"

[[dependencies.mgtlogin]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.mgtlogin]]
modId="mgtcore"
type="required"
versionRange="[1.0.1-SNAPSHOT,)"
ordering="AFTER"
side="BOTH"