name: Notificar Discord com commits

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar commits para o Discord
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_URL="https://github.com/${GITHUB_REPOSITORY}/tree/${BRANCH_NAME}"
          COUNT=$(jq '.commits | length' "$GITHUB_EVENT_PATH")
          AUTHOR="${GITHUB_ACTOR}"
          AUTHOR_URL="https://github.com/${AUTHOR}"
          AUTHOR_AVATAR="https://github.com/${AUTHOR}.png"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Lista de commits (hash curto, link, mensagem multilinha e autor)
          COMMITS=$(jq -r \
            '.commits[] | "[`\(.id[0:7])`](\(.url))\n\(.message)\n- \(.author.name)"' \
            "$GITHUB_EVENT_PATH")

          # Monta o payload com jq (seguro e com quebras de linha reais)
          jq -n \
            --arg username "MGT-GitHub" \
            --arg avatar "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" \
            --arg title "📢 Atualização no repositório" \
            --arg authorName "$AUTHOR" \
            --arg authorUrl "$AUTHOR_URL" \
            --arg authorIcon "$AUTHOR_AVATAR" \
            --arg repo   "📦 Repositório: ${GITHUB_REPOSITORY}" \
            --arg branch "🌿 Branch: [${BRANCH_NAME}](${BRANCH_URL})" \
            --arg count  "📌 ${COUNT} novo(s) commit(s):" \
            --arg commits "$COMMITS" \
            --arg time   "$TIMESTAMP" \
            '{
              username: $username,
              avatar_url: $avatar,
              embeds: [{
                title: $title,
                author: {
                  name: $authorName,
                  url: $authorUrl,
                  icon_url: $authorIcon
                },
                description: ($repo + "\n" + $branch + "\n" + $count + "\n\n" + $commits),
                color: 7506394,
                timestamp: $time
              }]
            }' \
          | curl -X POST -H "Content-Type: application/json" \
            -d @- ${{ secrets.DISCORD_WEBHOOK }}
